apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculator.fullname" . }}-ui
  labels:
    app: {{ include "calculator.name" . }}-ui
    {{- include "calculator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "calculator.name" . }}-ui
      {{- include "calculator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "calculator.name" . }}-ui
        {{- include "calculator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "calculator.name" . }}-ui
          image: ghcr.io/vermavarun/calculation-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
              protocol: TCP
          env:
            - name: REACT_APP_API_URL
              value: http://localhost:3000
            - name: PORT
              value: "5001"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
        - name: node-api
          image: ghcr.io/vermavarun/calculation-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: APP_SERVICE_URL
              value: http://ms-api:80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"