apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculator.fullname" . }}-api
  labels:
    app: {{ include "calculator.name" . }}-api
    {{- include "calculator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "calculator.name" . }}-api
      {{- include "calculator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "calculator.name" . }}-api
        {{- include "calculator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "calculator.name" . }}-api
          image: ghcr.io/vermavarun/calculation-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"