apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculator.fullname" . }}-api
  labels:
    app: {{ include "calculator.name" . }}-api
    {{- include "calculator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: {{ include "calculator.name" . }}-api
    {{- include "calculator.selectorLabels" . | nindent 4 }}