apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculator.fullname" . }}-ui
  labels:
    app: {{ include "calculator.name" . }}-ui
    {{- include "calculator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 1234
      targetPort: 5001
      protocol: TCP
      name: ui-port
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: node-port
  type: LoadBalancer
  selector:
    app: {{ include "calculator.name" . }}-ui
    {{- include "calculator.selectorLabels" . | nindent 4 }}