apiVersion: v1
kind: Service
metadata:
  name: react-ui
  labels:
    app: react-ui
    service: react-ui
spec:
  ports:
    - port: 1234
      targetPort: 5001
      protocol: TCP
      name: ui-port
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: node-port
  type: LoadBalancer
  selector:
    service: react-ui