apiVersion: v1
kind: Service
metadata:
  name: ms-api
  labels:
    app: ms-api
    service: webapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    service: ms-api