name: Build and Push Docker Images

on:
  push:
    branches: [ main, develop ]
    paths: [ 'images/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'images/**' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - image: calculation-ui
            context: ./images/calculation-ui
            dockerfile: ./images/calculation-ui/Dockerfile
          - image: calculation-api
            context: ./images/calculation-apis/calculations
            dockerfile: ./images/calculation-apis/calculations/Dockerfile
          - image: calculation-proxy
            context: ./images/calculation-apis/proxy-for-calculations
            dockerfile: ./images/calculation-apis/proxy-for-calculations/Dockerfile

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ matrix.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ matrix.image }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64