name: Publish Helm Chart to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '!charts/**/*.md'

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Enable OCI support
        run: |
          helm registry login ghcr.io -u ${{ github.actor }} --password-stdin <<< "${{ secrets.CR_PAT }}"

      - name: Package and Push Helm Chart
        run: |
          for CHART_DIR in charts/*/; do
            if [ -f "${CHART_DIR}Chart.yaml" ]; then
              CHART_NAME=$(basename "$CHART_DIR")
              VERSION=$(grep '^version:' "${CHART_DIR}Chart.yaml" | awk '{print $2}')
              # Package chart
              helm package "$CHART_DIR" --destination ./
              # Export to OCI-compatible format
              helm push "${CHART_NAME}-${VERSION}.tgz" oci://ghcr.io/${{ env.OWNER }}
            fi
          done
